#!/usr/bin/env python3
"""Spec 225 Part 1: any-player profile pipeline.

One command turns a named player into the full data/rivals artifact set:

    <slug>.pgn          merged corpus, every game with Source/SourceDate headers
    <slug>.SOURCES.md   provenance (never overwrites a hand-written one)
    <slug>.stats.json   stats dossier: colors, results, opening families,
                        phase win/loss profile
    <slug>.profile.json identity + sample verdict — the single honesty record
                        every consumer renders from
    <slug>.book.json    opening book (build_rival_book.py machinery, generalized)
    <slug>.config.json  persona config (build_rival_configs.py schema) — ONLY
                        when the sample-honesty gates allow it

Inputs: a display name plus any of FIDE ID (metadata only — FIDE publishes no
game archive), chess.com username (fetched via scripts/fetch_chesscom.py),
lichess username (scripts/fetch_lichess.py), and/or PGN files (the OTB import
path — the arnthor corpus precedent).

Sample-honesty gates (spec 225, named constants below, calibrated on dad's
47-game book):
    >= 30 usable games  -> full persona (book + dossier + config)
    10..29              -> persona allowed but LOW-CONFIDENCE badged in config
    < 10                -> dossier only, NO config, verdict says why
The verdict (count, thresholds, badge) is stored in <slug>.profile.json and
echoed into <slug>.config.json so every surface renders the same honesty.
`--unverified-event REGEX` marks games whose attribution is unconfirmed (the
arnthor Sweden-block case): they stay in the corpus/dossier but do not count
toward the persona floor. `--dossier-only REASON` blocks the persona outright
(e.g. corpus still in user-review staging) and records the reason.

data/rivals is gitignored (spec 214 hard rule — private individuals stay
LOCAL); this script refuses to write there if that ever stops being true.

Usage:
    build_player_profile.py "Arnthor Einarsson" --pgn data/rivals/arnthor-einarsson.pgn \
        --fide-id 2300540 --unverified-event Sweden --dossier-only "STAGING: user review pending"
    build_player_profile.py "Some Friend" --chesscom somefriend --lichess some_friend
    build_player_profile.py --self-test
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import chess
import chess.pgn

import build_rival_book as book_builder  # sibling module: harvest/exclusion/book doc

REPO_ROOT = Path(__file__).resolve().parents[2]
RIVALS_DIR = REPO_ROOT / "data" / "rivals"
SCRIPTS_DIR = REPO_ROOT / "scripts"

# --- Sample-honesty gates (spec 225) — the constants, not vibes in UI copy ---
FULL_PERSONA_FLOOR = 30  # >= this many verified games: full persona
PERSONA_MIN_GAMES = 10   # below this: dossier only, no persona config

VERDICT_FULL = "full"
VERDICT_LOW = "low-confidence"
VERDICT_DOSSIER = "dossier-only"
BADGES = {VERDICT_FULL: None, VERDICT_LOW: "LOW-CONFIDENCE", VERDICT_DOSSIER: "DOSSIER-ONLY"}

# Phase boundaries by ply — same convention as acpl_report.py (book/middle/end).
OPENING_MAX_PLY = 24
MIDDLE_MAX_PLY = 80

# Maia policy bands — same set as build_rival_configs.py / src-tauri maia.rs.
MAIA_BANDS = [1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900]
DEFAULT_RATING = 1500  # used (and honestly labeled) only when no rating is found

SOURCES_MARKER = "<!-- generated by build_player_profile.py -->"


# ---------------------------------------------------------------------------
# Options
# ---------------------------------------------------------------------------

@dataclass
class Options:
    name: str
    slug: str
    fide_id: str | None = None
    chesscom: str | None = None
    lichess: str | None = None
    pgns: list[Path] = field(default_factory=list)
    aliases: list[str] = field(default_factory=list)
    out_dir: Path = RIVALS_DIR
    rating: int | None = None
    rating_source: str | None = None
    relationship: str = "player"
    unverified_event: str | None = None
    dossier_only: str | None = None
    max_ply: int = book_builder.MAX_PLY
    since: str | None = None
    time_class: str | None = None


def slugify(name: str) -> str:
    s = name.strip().lower()
    # Icelandic/latin-1 folds seen in existing slugs (arnthor-einarsson precedent).
    for a, b in (("þ", "th"), ("ð", "d"), ("æ", "ae"), ("ö", "o"), ("á", "a"),
                 ("é", "e"), ("í", "i"), ("ó", "o"), ("ú", "u"), ("ý", "y")):
        s = s.replace(a, b)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "player"


# ---------------------------------------------------------------------------
# Player matching — headers carry usernames online and "First Last" /
# "Last, First" over the board; match any known alias in either form.
# ---------------------------------------------------------------------------

def _norm_name(s: str) -> str:
    s = " ".join(s.strip().lower().split())
    if "," in s:  # "Einarsson, Arnthor" -> "arnthor einarsson"
        last, _, first = s.partition(",")
        s = f"{first.strip()} {last.strip()}"
    return s


def alias_set(opts: Options) -> set[str]:
    names = [opts.name] + opts.aliases
    for u in (opts.chesscom, opts.lichess):
        if u:
            names.append(u)
    return {_norm_name(n) for n in names if n and n.strip()}


def player_color(game: chess.pgn.Game, aliases: set[str]) -> str | None:
    if _norm_name(game.headers.get("White", "")) in aliases:
        return "white"
    if _norm_name(game.headers.get("Black", "")) in aliases:
        return "black"
    return None


# ---------------------------------------------------------------------------
# Corpus assembly: fetch/import -> provenance headers -> dedupe
# ---------------------------------------------------------------------------

@dataclass
class SourceRecord:
    kind: str      # "chess.com" | "lichess" | "pgn"
    detail: str    # username or file path
    path: Path     # PGN on disk
    games: int = 0     # games in the file
    matched: int = 0   # games where the player was identified


def run_fetcher(script: str, user: str, out: Path, opts: Options) -> None:
    cmd = [sys.executable, str(SCRIPTS_DIR / script), user, "-o", str(out)]
    if opts.since:
        cmd += ["--since", opts.since]
    if opts.time_class:
        cmd += ["--time-class", opts.time_class]
    subprocess.run(cmd, check=True)


def gather_sources(opts: Options, tmpdir: Path) -> list[SourceRecord]:
    sources: list[SourceRecord] = []
    if opts.chesscom:
        p = tmpdir / f"{opts.slug}.chesscom.pgn"
        run_fetcher("fetch_chesscom.py", opts.chesscom, p, opts)
        sources.append(SourceRecord("chess.com", opts.chesscom, p))
    if opts.lichess:
        p = tmpdir / f"{opts.slug}.lichess.pgn"
        run_fetcher("fetch_lichess.py", opts.lichess, p, opts)
        sources.append(SourceRecord("lichess", opts.lichess, p))
    for pgn in opts.pgns:
        sources.append(SourceRecord("pgn", str(pgn), Path(pgn)))
    return sources


def read_games(path: Path) -> list[chess.pgn.Game]:
    games = []
    with open(path, encoding="utf-8", errors="replace") as fh:
        while True:
            g = chess.pgn.read_game(fh)
            if g is None:
                break
            games.append(g)
    return games


def ensure_provenance(game: chess.pgn.Game, fallback: str, stamp: str) -> None:
    """Every corpus game keeps Source + SourceDate (arnthor SOURCES.md precedent).
    chess.com PGNs carry [Link], lichess carries a URL [Site]; either is the source."""
    if not game.headers.get("Source"):
        link = game.headers.get("Link", "")
        site = game.headers.get("Site", "")
        url = link if link.startswith("http") else (site if site.startswith("http") else "")
        game.headers["Source"] = url or fallback
    if not game.headers.get("SourceDate"):
        game.headers["SourceDate"] = stamp


def dedupe_key(game: chess.pgn.Game) -> str:
    src = game.headers.get("Source", "")
    if src.startswith("http"):
        return src
    raw = "|".join((game.headers.get("White", ""), game.headers.get("Black", ""),
                    game.headers.get("Date", ""), game.headers.get("Result", ""),
                    " ".join(m.uci() for m in game.mainline_moves())))
    return hashlib.sha256(raw.encode()).hexdigest()


@dataclass
class Corpus:
    games: list[tuple[chess.pgn.Game, str]] = field(default_factory=list)  # (game, color)
    dropped_unmatched: int = 0
    duplicates: int = 0
    sources: list[SourceRecord] = field(default_factory=list)


def assemble_corpus(opts: Options, sources: list[SourceRecord]) -> Corpus:
    aliases = alias_set(opts)
    stamp = date.today().isoformat()
    corpus = Corpus(sources=sources)
    seen: set[str] = set()
    for src in sources:
        fallback = f"{src.kind}:{Path(src.detail).name if src.kind == 'pgn' else src.detail}"
        for game in read_games(src.path):
            src.games += 1
            color = player_color(game, aliases)
            if color is None:
                corpus.dropped_unmatched += 1
                continue
            src.matched += 1
            ensure_provenance(game, fallback, stamp)
            key = dedupe_key(game)
            if key in seen:
                corpus.duplicates += 1
                continue
            seen.add(key)
            corpus.games.append((game, color))
    return corpus


# ---------------------------------------------------------------------------
# Stats dossier: colors, results, opening families, phase win/loss profile
# ---------------------------------------------------------------------------

def opening_family(sans: list[str], headers: chess.pgn.Headers) -> str:
    """Coarse family label. Prefers the PGN's own Opening header (lichess /
    chess.com online games carry one); falls back to a first-moves table
    (OTB corpora like arnthor's carry no ECO/Opening headers)."""
    opening = headers.get("Opening", "").strip()
    if opening and opening != "?":
        return opening.split(":")[0].split(",")[0].strip()
    if not sans:
        return "unknown"
    first, reply = sans[0], (sans[1] if len(sans) > 1 else "")
    if first == "e4":
        return {"c5": "Sicilian", "e5": "Open Game (1.e4 e5)", "e6": "French",
                "c6": "Caro-Kann", "d6": "Pirc/Modern", "g6": "Pirc/Modern",
                "d5": "Scandinavian", "Nf6": "Alekhine"}.get(reply, "Other 1.e4")
    if first == "d4":
        if reply == "d5":
            return "Queen's Gambit / Closed (1.d4 d5)"
        if reply == "Nf6":
            early = sans[2:6]
            if "g6" in early:
                return "Indian: KID/Grünfeld complex"
            if "e6" in early:
                return "Indian: Nimzo/QID complex"
            return "Indian (1.d4 Nf6)"
        return "Other 1.d4"
    return {"c4": "English", "Nf3": "Réti/Nf3 systems", "f4": "Bird",
            "b3": "Nimzo-Larsen", "g3": "King's fianchetto"}.get(first, "Irregular")


def _line_str(sans: list[str], plies: int) -> str:
    return " ".join(book_builder._san_with_number(i, s) for i, s in enumerate(sans[:plies]))


def ending_phase(total_plies: int) -> str:
    if total_plies <= OPENING_MAX_PLY:
        return "opening"
    if total_plies <= MIDDLE_MAX_PLY:
        return "middlegame"
    return "endgame"


def _wdl() -> dict:
    return {"wins": 0, "draws": 0, "losses": 0, "games": 0}


def _tally(bucket: dict, outcome: str | None) -> None:
    bucket["games"] += 1
    if outcome:
        bucket[outcome] += 1


def build_stats(opts: Options, corpus: Corpus) -> dict:
    overall, by_color = _wdl(), {"white": _wdl(), "black": _wdl()}
    phases = {"opening": _wdl(), "middlegame": _wdl(), "endgame": _wdl()}
    families: dict[str, dict[str, dict]] = {"white": {}, "black": {}}
    lines: dict[str, dict[str, int]] = {"white": {}, "black": {}}
    elos: list[int] = []
    dates: list[str] = []

    for game, color in corpus.games:
        sans, board = [], game.board()
        for move in game.mainline_moves():
            try:
                sans.append(board.san(move))
            except (ValueError, AssertionError):
                break
            board.push(move)

        result = game.headers.get("Result", "*")
        outcome = None  # "wins" | "draws" | "losses" from the player's side
        if result == "1/2-1/2":
            outcome = "draws"
        elif result in ("1-0", "0-1"):
            won_white = result == "1-0"
            outcome = "wins" if (won_white == (color == "white")) else "losses"

        _tally(overall, outcome)
        _tally(by_color[color], outcome)
        _tally(phases[ending_phase(len(sans))], outcome)

        fam = families[color].setdefault(opening_family(sans, game.headers), _wdl())
        _tally(fam, outcome)
        line = _line_str(sans, 6)
        if line:
            lines[color][line] = lines[color].get(line, 0) + 1

        elo = game.headers.get("WhiteElo" if color == "white" else "BlackElo", "")
        if elo.isdigit():
            elos.append(int(elo))
        d = game.headers.get("Date", "")
        if d and not d.startswith("?"):
            dates.append(d)

    def top_families(color: str) -> list[dict]:
        return [{"family": f, **w}
                for f, w in sorted(families[color].items(),
                                   key=lambda kv: -kv[1]["games"])]

    def top_lines(color: str) -> list[dict]:
        return [{"line": l, "games": n}
                for l, n in sorted(lines[color].items(), key=lambda kv: (-kv[1], kv[0]))[:10]]

    total = overall["games"]
    decided = overall["wins"] + overall["draws"] + overall["losses"]
    score = (overall["wins"] + overall["draws"] / 2) / decided if decided else None
    rating = rating_verdict(opts, elos)
    return {
        "version": 1,
        "generated_at": int(time.time()),
        "generator": "scripts/persona/build_player_profile.py",
        "slug": opts.slug,
        "display_name": opts.name,
        "games": {"total": total,
                  "as_white": by_color["white"]["games"],
                  "as_black": by_color["black"]["games"]},
        "results": {**{k: overall[k] for k in ("wins", "draws", "losses")},
                    "score_pct": round(score * 100, 1) if score is not None else None,
                    "as_white": by_color["white"], "as_black": by_color["black"]},
        "opening_families": {"as_white": top_families("white"),
                             "as_black": top_families("black")},
        "top_lines": {"as_white": top_lines("white"), "as_black": top_lines("black")},
        "phase_profile": {
            "boundaries": {"opening_max_ply": OPENING_MAX_PLY,
                           "middlegame_max_ply": MIDDLE_MAX_PLY},
            "ended_in": phases,
        },
        "rating": rating,
        "date_range": {"first": min(dates), "last": max(dates)} if dates else None,
    }


def rating_verdict(opts: Options, corpus_elos: list[int]) -> dict:
    if opts.rating is not None:
        return {"value": opts.rating,
                "source": opts.rating_source or "provided via --rating"}
    if corpus_elos:
        mean = round(sum(corpus_elos) / len(corpus_elos))
        return {"value": mean,
                "source": f"corpus Elo headers (mean of {len(corpus_elos)} games)"}
    return {"value": None, "source": "no rating found"}


# ---------------------------------------------------------------------------
# Sample verdict — the honesty record (spec 225)
# ---------------------------------------------------------------------------

def sample_verdict(opts: Options, corpus: Corpus) -> dict:
    total = len(corpus.games)
    unverified = 0
    if opts.unverified_event:
        rx = re.compile(opts.unverified_event, re.IGNORECASE)
        unverified = sum(1 for g, _ in corpus.games if rx.search(g.headers.get("Event", "")))
    verified = total - unverified

    reasons: list[str] = []
    if opts.dossier_only:
        verdict = VERDICT_DOSSIER
        reasons.append(opts.dossier_only)
    elif verified < PERSONA_MIN_GAMES:
        verdict = VERDICT_DOSSIER
        reasons.append(f"{verified} verified games < persona minimum {PERSONA_MIN_GAMES}")
    elif verified < FULL_PERSONA_FLOOR:
        verdict = VERDICT_LOW
        reasons.append(f"{verified} verified games < full-persona floor {FULL_PERSONA_FLOOR}")
    else:
        verdict = VERDICT_FULL
    if unverified:
        reasons.append(f"{unverified} games match unverified-event rule "
                       f"/{opts.unverified_event}/ and do not count toward the floor")

    return {
        "games": total,
        "verified_games": verified,
        "unverified_games": unverified,
        "unverified_rule": opts.unverified_event,
        "thresholds": {"full_persona_floor": FULL_PERSONA_FLOOR,
                       "persona_min_games": PERSONA_MIN_GAMES},
        "verdict": verdict,
        "badge": BADGES[verdict],
        "reasons": reasons,
    }


# ---------------------------------------------------------------------------
# Book + persona config (reusing the spec 214 machinery/schemas)
# ---------------------------------------------------------------------------

def build_book(opts: Options, corpus: Corpus, corpus_path: Path) -> dict:
    entries: "OrderedDict[tuple[str, str], book_builder.Entry]" = OrderedDict()
    stats = book_builder.BuildStats()
    for game, color in corpus.games:
        stats.games += 1
        if not book_builder.is_standard_start(game):
            stats.skipped_non_standard += 1
            continue
        if book_builder.harvest_game(game, color, entries, opts.max_ply):
            stats.used += 1
    stats.sources.append({"username": opts.name, "path": str(corpus_path),
                          "games": stats.games})
    ordered = sorted(entries.values(), key=lambda e: (-e.weight, e.ply, e.line))
    return book_builder.to_document(ordered, stats, rival=opts.slug, max_ply=opts.max_ply)


def nearest_band(rating: int) -> int:
    return min(MAIA_BANDS, key=lambda b: abs(b - rating))


def build_config(opts: Options, book: dict, verdict: dict, rating: dict) -> dict:
    """Persona config, build_rival_configs.py schema + the sample-honesty block."""
    rv = rating["value"] if rating["value"] is not None else DEFAULT_RATING
    band = nearest_band(rv)
    band_source = (f"{rating['source']} rating {rating['value']} -> nearest Maia band"
                   if rating["value"] is not None
                   else f"default {DEFAULT_RATING} (no rating found) -> nearest Maia band")
    low = verdict["verdict"] == VERDICT_LOW
    note = ("NOT harness-measured (too few games / private individual). Realism "
            "comes from the opening book + Maia policy; validated only by the "
            "in-app 'felt like him' feedback capture.")
    if low:
        note = (f"LOW-CONFIDENCE sample ({verdict['verified_games']} verified games "
                f"< {FULL_PERSONA_FLOOR}). " + note)
    return {
        "version": 1,
        "slug": opts.slug,
        "display_name": opts.name,
        "kind": "private-rival",
        "relationship": opts.relationship,
        "book": {"path": f"data/rivals/{opts.slug}.book.json",
                 "max_ply": book["max_ply"],
                 "positions": book["stats"]["positions"],
                 "games": book["stats"]["games_used"]},
        "backend": {"kind": "maia", "level": band, "net": f"maia-{band}.pb.gz"},
        "runnable_in_engine_v1": True,
        "sampling": {"level": band, "temperature": 0.5, "alpha": 1.0,
                     "lambda": 0.75, "top_k": 4, "verify_depth": 12},
        "strength_label": {"kind": "book + Maia band, unmeasured",
                           "maia_band": band, "band_source": band_source,
                           "note": note},
        "low_confidence": low,
        "sample": verdict,
        "private": True,
    }


# ---------------------------------------------------------------------------
# Artifact writing
# ---------------------------------------------------------------------------

def assert_writable(out_dir: Path) -> None:
    """Refuse to write inside the repo unless the target is gitignored
    (spec 214 guard, same as build_rival_configs.py). Paths outside the repo
    (self-test tmp dirs) are exempt."""
    try:
        rel = out_dir.resolve().relative_to(REPO_ROOT)
    except ValueError:
        return
    r = subprocess.run(["git", "-C", str(REPO_ROOT), "check-ignore", "-q",
                        str(rel / "probe.config.json")])
    if r.returncode != 0:
        raise SystemExit(f"REFUSING: {rel} is not gitignored — private player "
                         "profiles must never be committable (spec 214).")


def write_corpus(corpus: Corpus, out_pgn: Path) -> bool:
    """Write the merged corpus. Skipped (returns False) when the corpus was read
    in-place from out_pgn itself with no other sources — never rewrite a staged,
    hand-provenanced file just to reformat it."""
    in_place = (len(corpus.sources) == 1 and corpus.sources[0].kind == "pgn"
                and Path(corpus.sources[0].detail).resolve() == out_pgn.resolve())
    if in_place:
        return False
    exporter_text = []
    for game, _ in corpus.games:
        exporter_text.append(str(game).rstrip())
    out_pgn.write_text("\n\n".join(exporter_text) + "\n", encoding="utf-8")
    return True


def write_sources_md(opts: Options, corpus: Corpus, path: Path, corpus_written: bool) -> bool:
    """Generated provenance file. A hand-written SOURCES.md (no marker line —
    the arnthor precedent) is never touched."""
    if path.exists() and SOURCES_MARKER not in path.read_text(encoding="utf-8"):
        return False
    ids = [f"FIDE {opts.fide_id}" if opts.fide_id else None,
           f"chess.com `{opts.chesscom}`" if opts.chesscom else None,
           f"lichess `{opts.lichess}`" if opts.lichess else None]
    ids_str = ", ".join(i for i in ids if i) or "no external IDs recorded"
    rows = "\n".join(f"| {s.kind} | {s.detail} | {s.games} | {s.matched} |"
                     for s in corpus.sources)
    body = f"""# Provenance — {opts.slug}.pgn
{SOURCES_MARKER}

**Player:** {opts.name} ({ids_str})
**Assembled:** {date.today().isoformat()} by scripts/persona/build_player_profile.py.
Directory is gitignored; never commit (spec 214 hard rule).

## Sources

| kind | detail | games in source | games matched to player |
|---|---|---|---|
{rows}

Corpus: {len(corpus.games)} games kept ({corpus.duplicates} duplicates removed,
{corpus.dropped_unmatched} games dropped where the player was not identified).
Every kept game carries `[Source]` and `[SourceDate]` headers.
{"" if corpus_written else "Corpus file was reused in place (single PGN source); not rewritten."}
"""
    path.write_text(body, encoding="utf-8")
    return True


def _write_json(path: Path, doc: dict) -> None:
    path.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------

def run_pipeline(opts: Options) -> dict:
    """Runs the whole pipeline; returns the profile document (also written to
    <slug>.profile.json)."""
    if not (opts.chesscom or opts.lichess or opts.pgns):
        raise SystemExit("no game sources: pass --chesscom, --lichess and/or --pgn "
                         "(a FIDE ID alone carries no games — FIDE has no game archive)")
    opts.out_dir.mkdir(parents=True, exist_ok=True)
    assert_writable(opts.out_dir)

    with tempfile.TemporaryDirectory(prefix="player-profile-") as td:
        sources = gather_sources(opts, Path(td))
        corpus = assemble_corpus(opts, sources)

        out_pgn = opts.out_dir / f"{opts.slug}.pgn"
        corpus_written = write_corpus(corpus, out_pgn)
        sources_path = opts.out_dir / f"{opts.slug}.SOURCES.md"
        sources_written = write_sources_md(opts, corpus, sources_path, corpus_written)

    stats = build_stats(opts, corpus)
    _write_json(opts.out_dir / f"{opts.slug}.stats.json", stats)

    book = build_book(opts, corpus, out_pgn)
    _write_json(opts.out_dir / f"{opts.slug}.book.json", book)

    verdict = sample_verdict(opts, corpus)
    config_path = opts.out_dir / f"{opts.slug}.config.json"
    if verdict["verdict"] == VERDICT_DOSSIER:
        # No persona below the floor (or while staged): make sure a stale config
        # from an earlier, larger-looking sample can't outlive the verdict.
        config_path.unlink(missing_ok=True)
        config_emitted = False
    else:
        _write_json(config_path, build_config(opts, book, verdict, stats["rating"]))
        config_emitted = True

    profile = {
        "version": 1,
        "generated_at": int(time.time()),
        "generator": "scripts/persona/build_player_profile.py",
        "slug": opts.slug,
        "display_name": opts.name,
        "relationship": opts.relationship,
        "identity": {"fide_id": opts.fide_id, "chesscom": opts.chesscom,
                     "lichess": opts.lichess},
        "sample": verdict,
        "rating": stats["rating"],
        "artifacts": {
            "pgn": f"data/rivals/{opts.slug}.pgn",
            "sources_md": f"data/rivals/{opts.slug}.SOURCES.md",
            "stats": f"data/rivals/{opts.slug}.stats.json",
            "book": f"data/rivals/{opts.slug}.book.json",
            "config": f"data/rivals/{opts.slug}.config.json" if config_emitted else None,
        },
        "notes": {
            "corpus_rewritten": corpus_written,
            "sources_md_written": sources_written,
        },
    }
    _write_json(opts.out_dir / f"{opts.slug}.profile.json", profile)

    print(f"{opts.slug}: {verdict['games']} games "
          f"({verdict['verified_games']} verified) -> verdict {verdict['verdict'].upper()}")
    for r in verdict["reasons"]:
        print(f"  - {r}")
    print(f"  book: {book['stats']['positions']} positions from "
          f"{book['stats']['games_used']} games (max_ply {book['max_ply']})")
    print(f"  config: {'written' if config_emitted else 'NOT emitted (dossier-only)'}")
    return profile


# ---------------------------------------------------------------------------
# Self-test — synthetic fixture games only (never real family data). Exercises
# the gates, provenance, dedupe and in-place preservation end to end.
# ---------------------------------------------------------------------------

_FIXTURE_LINES = [
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be2 e5 Nb3 Be7 O-O O-O".split(),
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5 O-O Nc6 d5 Ne7".split(),
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6 Be2 Bb7".split(),
    "c4 e5 Nc3 Nf6 Nf3 Nc6 g3 d5 cxd5 Nxd5 Bg2 Nb6 O-O Be7 d3 O-O".split(),
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O".split(),
]
_RESULTS = ["1-0", "0-1", "1/2-1/2"]


def _fixture_pgn(n_games: int, player: str, event: str = "Fixture Open",
                 start_index: int = 0) -> str:
    """n distinct, legal games with `player` alternating colors."""
    out = []
    for i in range(n_games):
        k = start_index + i
        game = chess.pgn.Game()
        white, black = (player, f"Opponent {k}") if k % 2 == 0 else (f"Opponent {k}", player)
        game.headers["Event"] = event
        game.headers["Site"] = "Selftest"
        game.headers["Date"] = f"2024.01.{(k % 28) + 1:02d}"
        game.headers["Round"] = str(k + 1)
        game.headers["White"] = white
        game.headers["Black"] = black
        game.headers["Result"] = _RESULTS[k % 3]
        game.headers["WhiteElo"] = "1620"
        game.headers["BlackElo"] = "1580"
        node = game
        for san in _FIXTURE_LINES[k % len(_FIXTURE_LINES)]:
            node = node.add_variation(node.board().parse_san(san))
        out.append(str(game))
    return "\n\n".join(out) + "\n"


def _run_fixture(td: Path, name: str, n: int, tag: str, **kw) -> tuple[dict, Path]:
    fixture = td / f"{tag}.fixture.pgn"
    fixture.write_text(_fixture_pgn(n, name), encoding="utf-8")
    out_dir = td / f"{tag}.out"
    opts = Options(name=name, slug=slugify(f"{name} {tag}"), pgns=[fixture],
                   out_dir=out_dir, **kw)
    return run_pipeline(opts), out_dir


def self_test() -> int:
    ok = True

    def check(cond: bool, msg: str):
        nonlocal ok
        print(f"  [{'PASS' if cond else 'FAIL'}] {msg}")
        if not cond:
            ok = False

    with tempfile.TemporaryDirectory(prefix="bpp-selftest-") as td_s:
        td = Path(td_s)
        name = "Testy Fixture"

        # Gate 1: >= 30 games -> full persona.
        profile, out = _run_fixture(td, name, 35, "full")
        slug = profile["slug"]
        check(profile["sample"]["verdict"] == VERDICT_FULL, "35 games -> verdict full")
        check((out / f"{slug}.config.json").exists(), "full: config.json emitted")
        cfg = json.loads((out / f"{slug}.config.json").read_text())
        check(cfg["low_confidence"] is False, "full: config not low-confidence")
        check(cfg["sample"]["verdict"] == VERDICT_FULL, "full: verdict echoed in config")
        for ext in ("pgn", "SOURCES.md", "stats.json", "book.json", "profile.json"):
            check((out / f"{slug}.{ext}").exists(), f"full: {ext} emitted")

        # Provenance: every corpus game has Source + SourceDate.
        games = read_games(out / f"{slug}.pgn")
        check(len(games) == 35, "full: corpus keeps all 35 games")
        check(all(g.headers.get("Source") and g.headers.get("SourceDate") for g in games),
              "full: every game carries Source + SourceDate")

        # Stats dossier shape.
        stats = json.loads((out / f"{slug}.stats.json").read_text())
        check(stats["games"]["total"] == 35
              and stats["games"]["as_white"] + stats["games"]["as_black"] == 35,
              "full: stats colors add up")
        check(stats["results"]["wins"] + stats["results"]["draws"]
              + stats["results"]["losses"] == 35, "full: stats results add up")
        check(bool(stats["opening_families"]["as_white"]), "full: opening families present")
        phases = stats["phase_profile"]["ended_in"]
        check(sum(p["games"] for p in phases.values()) == 35, "full: phase profile adds up")

        # Gate 2: 10..29 -> LOW-CONFIDENCE config.
        profile, out = _run_fixture(td, name, 12, "low")
        slug = profile["slug"]
        check(profile["sample"]["verdict"] == VERDICT_LOW, "12 games -> verdict low-confidence")
        check(profile["sample"]["badge"] == "LOW-CONFIDENCE", "low: badge recorded")
        cfg = json.loads((out / f"{slug}.config.json").read_text())
        check(cfg["low_confidence"] is True, "low: config flagged low_confidence")
        check("LOW-CONFIDENCE" in cfg["strength_label"]["note"], "low: label says so")

        # Gate 3: < 10 -> dossier only, no config, reason recorded.
        profile, out = _run_fixture(td, name, 5, "tiny")
        slug = profile["slug"]
        check(profile["sample"]["verdict"] == VERDICT_DOSSIER, "5 games -> dossier-only")
        check(not (out / f"{slug}.config.json").exists(), "tiny: no config emitted")
        check(profile["artifacts"]["config"] is None, "tiny: profile says config absent")
        check(any("persona minimum" in r for r in profile["sample"]["reasons"]),
              "tiny: verdict says why")
        check((out / f"{slug}.book.json").exists() and (out / f"{slug}.stats.json").exists(),
              "tiny: dossier (stats + book) still emitted")

        # Unverified-event rule: attributed games don't count toward the floor.
        fixture = td / "mixed.fixture.pgn"
        fixture.write_text(_fixture_pgn(28, name) + "\n"
                           + _fixture_pgn(7, name, event="Sweden Open", start_index=28),
                           encoding="utf-8")
        out = td / "mixed.out"
        profile = run_pipeline(Options(name=name, slug="testy-mixed", pgns=[fixture],
                                       out_dir=out, unverified_event="Sweden"))
        s = profile["sample"]
        check(s["games"] == 35 and s["unverified_games"] == 7 and s["verified_games"] == 28,
              "unverified rule: 35 total / 28 verified")
        check(s["verdict"] == VERDICT_LOW, "unverified rule: 28 verified -> low-confidence")

        # --dossier-only blocks the persona regardless of count, and removes a
        # stale config left from an earlier run.
        check((out / "testy-mixed.config.json").exists(), "stale-config precondition")
        profile = run_pipeline(Options(name=name, slug="testy-mixed", pgns=[fixture],
                                       out_dir=out, unverified_event="Sweden",
                                       dossier_only="STAGING: review pending"))
        check(profile["sample"]["verdict"] == VERDICT_DOSSIER
              and "STAGING: review pending" in profile["sample"]["reasons"],
              "--dossier-only: verdict + reason recorded")
        check(not (out / "testy-mixed.config.json").exists(),
              "--dossier-only: stale config removed")

        # Dedupe: the same fixture passed twice yields one copy of each game.
        out = td / "dupes.out"
        f1 = td / "full.fixture.pgn"
        profile = run_pipeline(Options(name=name, slug="testy-dupes", pgns=[f1, f1],
                                       out_dir=out))
        check(profile["sample"]["games"] == 35, "dedupe: duplicate source collapses")

        # In-place: running on an existing staged corpus (hand-written
        # SOURCES.md, no marker) rewrites neither the PGN nor the provenance.
        out = td / "inplace.out"
        out.mkdir()
        staged_pgn = out / "testy-staged.pgn"
        staged_pgn.write_text(_fixture_pgn(11, name), encoding="utf-8")
        staged_sources = out / "testy-staged.SOURCES.md"
        staged_sources.write_text("# hand-written provenance\n", encoding="utf-8")
        pgn_before, md_before = staged_pgn.read_text(), staged_sources.read_text()
        profile = run_pipeline(Options(name=name, slug="testy-staged",
                                       pgns=[staged_pgn], out_dir=out))
        check(staged_pgn.read_text() == pgn_before, "in-place: corpus PGN untouched")
        check(staged_sources.read_text() == md_before, "in-place: hand-written SOURCES.md untouched")
        check(profile["notes"] == {"corpus_rewritten": False, "sources_md_written": False},
              "in-place: profile records the preservation")

        # Book sanity: entries respect max_ply and carry weights.
        book = json.loads((td / "full.out" / f"{slugify(name + ' full')}.book.json").read_text())
        check(book["stats"]["positions"] > 0
              and all(e["ply"] <= book["max_ply"] for e in book["entries"]),
              "book: positions within max_ply")

    return 0 if ok else 1


# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Build the full data/rivals profile artifact set for any player (spec 225).")
    ap.add_argument("name", nargs="?", help='display name, e.g. "Arnthor Einarsson"')
    ap.add_argument("--slug", default=None, help="artifact slug (default: slugified name)")
    ap.add_argument("--fide-id", default=None, help="FIDE ID (identity metadata only)")
    ap.add_argument("--chesscom", default=None, help="chess.com username to fetch")
    ap.add_argument("--lichess", default=None, help="lichess username to fetch")
    ap.add_argument("--pgn", action="append", type=Path, default=[],
                    help="PGN file to import (repeatable — the OTB path)")
    ap.add_argument("--alias", action="append", default=[],
                    help="extra name form to match in PGN headers (repeatable)")
    ap.add_argument("--out-dir", type=Path, default=RIVALS_DIR)
    ap.add_argument("--rating", type=int, default=None,
                    help="rating override for Maia band choice (else corpus Elo mean)")
    ap.add_argument("--rating-source", default=None, help="where --rating came from")
    ap.add_argument("--relationship", default="player")
    ap.add_argument("--unverified-event", default=None, metavar="REGEX",
                    help="games whose Event matches stay in the dossier but do not "
                         "count toward the persona floor (attribution unconfirmed)")
    ap.add_argument("--dossier-only", default=None, metavar="REASON",
                    help="emit no persona config regardless of sample; REASON is "
                         "recorded in the verdict")
    ap.add_argument("--max-ply", type=int, default=book_builder.MAX_PLY,
                    help=f"book depth in plies (default {book_builder.MAX_PLY})")
    ap.add_argument("--since", default=None, help="fetchers: earliest month, YYYY-MM")
    ap.add_argument("--time-class", default=None, help="fetchers: comma list to keep")
    ap.add_argument("--self-test", action="store_true", help="run built-in checks and exit")
    args = ap.parse_args()

    if args.self_test:
        print("build_player_profile self-test:")
        return self_test()
    if not args.name:
        ap.error("name is required (or use --self-test)")

    missing = [str(p) for p in args.pgn if not p.exists()]
    if missing:
        print(f"error: PGN(s) not found: {', '.join(missing)}", file=sys.stderr)
        return 1

    opts = Options(name=args.name, slug=args.slug or slugify(args.name),
                   fide_id=args.fide_id, chesscom=args.chesscom, lichess=args.lichess,
                   pgns=args.pgn, aliases=args.alias, out_dir=args.out_dir,
                   rating=args.rating, rating_source=args.rating_source,
                   relationship=args.relationship,
                   unverified_event=args.unverified_event,
                   dossier_only=args.dossier_only, max_ply=args.max_ply,
                   since=args.since, time_class=args.time_class)
    run_pipeline(opts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
