// Calm positions for mixed Avoidance decks (spec 211: "some positions … are
// genuinely calm … the player must NOT learn 'there's always a trap'").
//
// Provenance: generated by scripts/mining/sample_calm.py — the cliff
// generator's NEGATIVE path. Each row comes from an eval-tagged game in
// data/reference/pack_2024-01_partial.pgn (the same reference pack the
// solver's rake fixtures were mined from) in which mine_cliffs.py finds ZERO
// cliff candidates, at a mid-game ply where [%eval] stays within ±0.6 across
// the surrounding plies. Every row was then re-verified with local Stockfish
// (depth 16, MultiPV 4, 2026-07-15): engine best within ±60cp AND ≥ 3 moves
// within 50cp of best — "many moves are fine" is the property being sold, so
// it is the property verified. Regenerate:
//
//   python3 scripts/mining/sample_calm.py data/reference/pack_2024-01_partial.pgn \
//       --engine /opt/homebrew/bin/stockfish --limit 24 --out calm.jsonl
//
// The batch is BUNDLED (22 rows) rather than imported into the puzzles table:
// the table's schema is a verbatim mirror of import_puzzles.py's (trap_uci
// NOT NULL, refutation required) and a calm row has neither — bending the
// schema for calm rows would break the mirror invariant. When calm supply
// graduates to the corpus scale, it gets its own table; for now a bundled
// set the deck-builder samples from is the honest size of the feature.
//
// ANTI-LEAK: nothing in this module may be shown to the user before they
// answer — which rows are calm is exactly the information the puzzle
// withholds (spec 211: the absence of the tell is the point).

/** One engine-verified calm position. Field names match PuzzleRow where the
 *  concepts coincide (mover-POV cp, same grading params). */
export type CalmRow = {
  /** Stable key "calm:<game_id>:<ply>" — the spaced-repetition identity. */
  id: string
  fen: string
  /** Stockfish best at engine_verify_depth, mover POV — grading baseline. */
  verified_pre_best_cp: number
  /** MultiPV moves within safe_threshold of best at verification time. */
  n_safe_moves: number
  safe_threshold: number
  engine_verify_depth: number
  mover: string
  ply: number
  band: string | null
  white_elo: number | null
  black_elo: number | null
  source_game_id: string | null
  site: string | null
  date: string | null
  time_control: string | null
}

export const CALM_POSITIONS: CalmRow[] = [
  { id: "calm:lO7WMpEK:16", fen: "r3kbnr/pp1b1ppp/1q2p3/3pP3/3n4/3B1N2/PP3PPP/RNBQ1RK1 w kq - 0 9", verified_pre_best_cp: -18, n_safe_moves: 3, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 16, band: "2000", white_elo: 2028, black_elo: 2021, source_game_id: "lO7WMpEK", site: "https://lichess.org/lO7WMpEK", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:1jzye0JY:27", fen: "r2q1rk1/pp2ppbp/2p1b1p1/8/8/2PP1NP1/P1Q1PPBP/1R3RK1 b - - 0 14", verified_pre_best_cp: 38, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 27, band: "2000", white_elo: 1979, black_elo: 2080, source_game_id: "1jzye0JY", site: "https://lichess.org/1jzye0JY", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:xziWtsSJ:24", fen: "rnb5/ppp2pkp/6p1/8/4r3/7P/PPP1NPP1/R3KB1R w KQ - 0 13", verified_pre_best_cp: 29, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 24, band: "2100", white_elo: 2119, black_elo: 2148, source_game_id: "xziWtsSJ", site: "https://lichess.org/xziWtsSJ", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:y2Ez04SY:25", fen: "r1bq1rk1/4bpp1/p1np1n1p/1ppNp3/4P2B/P2P1N2/BPP2PPP/R2Q1RK1 b - - 3 13", verified_pre_best_cp: 11, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 25, band: "2000", white_elo: 1908, black_elo: 2016, source_game_id: "y2Ez04SY", site: "https://lichess.org/y2Ez04SY", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:jT29itvo:17", fen: "r1bq1rk1/ppp2pbp/3p1np1/2nPp3/4P3/2NB1N1P/PPP2PP1/R1BQR1K1 b - - 2 9", verified_pre_best_cp: -18, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 17, band: "1900", white_elo: 1988, black_elo: 1900, source_game_id: "jT29itvo", site: "https://lichess.org/jT29itvo", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:w1fxnoSo:22", fen: "r2q1rk1/3nbppp/p2pbn2/1p2p3/4P1P1/1NN1BP2/PPPQ3P/2KR1B1R w - - 0 12", verified_pre_best_cp: 44, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 22, band: "2000", white_elo: 2015, black_elo: 1904, source_game_id: "w1fxnoSo", site: "https://lichess.org/w1fxnoSo", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:c6wXcZ9m:33", fen: "2kr1r2/6pp/p1p1bpn1/2p5/Pp2P3/4N3/1PP1NPPP/3RK2R b K - 5 17", verified_pre_best_cp: 58, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 33, band: "2100", white_elo: 2169, black_elo: 2198, source_game_id: "c6wXcZ9m", site: "https://lichess.org/c6wXcZ9m", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:c96AzSOr:19", fen: "r1b2rk1/pp1nppbp/1qp2np1/3p4/3P1B2/1QPBPN2/PP1N1PPP/R4RK1 b - - 4 10", verified_pre_best_cp: -29, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 19, band: "2000", white_elo: 2169, black_elo: 2078, source_game_id: "c96AzSOr", site: "https://lichess.org/c96AzSOr", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:5pWWxTHW:22", fen: "r1bq1rk1/ppppnppp/8/3P4/2B5/5N2/PP1Q1PPP/R4RK1 w - - 1 12", verified_pre_best_cp: 0, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 22, band: "2200", white_elo: 2269, black_elo: 2271, source_game_id: "5pWWxTHW", site: "https://lichess.org/5pWWxTHW", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:pH55RDE0:45", fen: "5rk1/p4pp1/1np1p2p/1p1r4/3P3P/PPP1BPP1/4R3/R5K1 b - - 2 23", verified_pre_best_cp: 10, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 45, band: "2300", white_elo: 2295, black_elo: 2381, source_game_id: "pH55RDE0", site: "https://lichess.org/pH55RDE0", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:tU9b58FW:18", fen: "r2q1rk1/ppp1bppp/2n1p3/1B3b2/3P4/2P2N2/P1P2PPP/R1BQ1RK1 w - - 4 10", verified_pre_best_cp: 9, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 18, band: "2000", white_elo: 2074, black_elo: 2063, source_game_id: "tU9b58FW", site: "https://lichess.org/tU9b58FW", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:0K4Y1R5j:17", fen: "r1bq1rk1/p4ppp/1pnbpn2/2pp4/3P4/2P1PNP1/PP1N1PBP/R1BQR1K1 b - - 5 9", verified_pre_best_cp: 21, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 17, band: "2100", white_elo: 2002, black_elo: 2147, source_game_id: "0K4Y1R5j", site: "https://lichess.org/0K4Y1R5j", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:10XXVT89:35", fen: "r3r1k1/1q2bppp/p3pn2/np1pN3/3P4/1PP2P1P/P3Q1PB/2R1RNK1 b - - 0 18", verified_pre_best_cp: 53, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 35, band: "2100", white_elo: 2094, black_elo: 2106, source_game_id: "10XXVT89", site: "https://lichess.org/10XXVT89", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:HOFpZ8Ux:16", fen: "r1bqkb1r/5ppp/p2ppn2/1pp1n3/4P3/P1NP4/BPP1QPPP/R1B1K1NR w KQkq - 0 9", verified_pre_best_cp: 7, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 16, band: "2000", white_elo: 2029, black_elo: 1949, source_game_id: "HOFpZ8Ux", site: "https://lichess.org/HOFpZ8Ux", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:9d3Hh69H:18", fen: "rn1q1rk1/1pp1bppp/p2p1n2/3Pp3/B3P1b1/2P2N2/PP3PPP/RNBQR1K1 w - - 1 10", verified_pre_best_cp: 43, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 18, band: "1900", white_elo: 1985, black_elo: 1968, source_game_id: "9d3Hh69H", site: "https://lichess.org/9d3Hh69H", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:0yhFYQ7N:48", fen: "3r2k1/5pp1/1p6/pBn1r3/P2Nb3/2R1P1Pp/5P1P/R5K1 w - - 4 25", verified_pre_best_cp: 30, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 48, band: "2300", white_elo: 2318, black_elo: 2192, source_game_id: "0yhFYQ7N", site: "https://lichess.org/0yhFYQ7N", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:TG0T6nNG:19", fen: "r3kb1r/1pq2ppp/p1bppn2/2p5/4PP2/2NP1N2/PPP3PP/R1B1QR1K b kq - 5 10", verified_pre_best_cp: 9, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 19, band: "2100", white_elo: 2083, black_elo: 2102, source_game_id: "TG0T6nNG", site: "https://lichess.org/TG0T6nNG", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:JMP3p2Xz:52", fen: "8/p4pkp/2p1p1p1/2P5/2PP4/8/Pr3PPP/4R1K1 w - - 3 27", verified_pre_best_cp: -3, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 52, band: "1900", white_elo: 1977, black_elo: 2030, source_game_id: "JMP3p2Xz", site: "https://lichess.org/JMP3p2Xz", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:nRPvVtMz:63", fen: "8/7k/1p4qp/2p5/5r2/1Q1P4/6PP/4R2K b - - 3 32", verified_pre_best_cp: 0, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 63, band: "2100", white_elo: 2164, black_elo: 2121, source_game_id: "nRPvVtMz", site: "https://lichess.org/nRPvVtMz", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:ehZ8IAyF:17", fen: "r2qkbnr/p2p1ppp/1pn1p3/8/3NP3/2N1B3/PPP2PPP/R2QKR2 b Qkq - 2 9", verified_pre_best_cp: -46, n_safe_moves: 3, safe_threshold: 50, engine_verify_depth: 16, mover: "black", ply: 17, band: "2100", white_elo: 2147, black_elo: 2146, source_game_id: "ehZ8IAyF", site: "https://lichess.org/ehZ8IAyF", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:oK39V7HV:18", fen: "r2qk2r/2p1n1pp/p1pbbp2/1p2p3/4P3/2NPBN1P/PPP1QPP1/R3K2R w KQkq - 0 10", verified_pre_best_cp: -27, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 18, band: "2100", white_elo: 2148, black_elo: 2321, source_game_id: "oK39V7HV", site: "https://lichess.org/oK39V7HV", date: "2024.01.01", time_control: "600+5" },
  { id: "calm:OLFM7VUb:56", fen: "5r2/1Q2Rpkp/6p1/4Nq2/p2P4/7P/1P3nPK/8 w - - 1 29", verified_pre_best_cp: 7, n_safe_moves: 4, safe_threshold: 50, engine_verify_depth: 16, mover: "white", ply: 56, band: "1900", white_elo: 1936, black_elo: 1926, source_game_id: "OLFM7VUb", site: "https://lichess.org/OLFM7VUb", date: "2024.01.01", time_control: "600+5" },
]

export function getCalm(id: string): CalmRow | null {
  return CALM_POSITIONS.find((c) => c.id === id) ?? null
}

/**
 * Sample `count` calm rows without replacement: band matches first, topped up
 * from the other bands when thin (same top-up contract as puzzles_deck).
 * `rng` is injectable for deterministic tests; order within each pool is
 * shuffled so a deck never leaks "the calm one is always the same position".
 */
export function calmDeck(
  band: string | null,
  count: number,
  excludeIds: ReadonlySet<string> = new Set(),
  rng: () => number = Math.random,
): CalmRow[] {
  const pool = CALM_POSITIONS.filter((c) => !excludeIds.has(c.id))
  const inBand = band ? pool.filter((c) => c.band === band) : pool
  const rest = band ? pool.filter((c) => c.band !== band) : []
  return [...shuffle(inBand, rng), ...shuffle(rest, rng)].slice(0, Math.max(count, 0))
}

function shuffle<T>(items: readonly T[], rng: () => number): T[] {
  const a = [...items]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}
